### ISSUE TITLE
Missing XEP and version supported

### ISSUE THREAD

**Issue by Neustradamus** [davidmuradov/falcon#2]
Can you add the supported XEP and what version?
- https://xmpp.org/extensions/xep-0384.html
- https://xmpp.org/extensions/xep-0454.html

Thanks in advance.

**Comment by davidmuradov** [comment]
Hello,

I'll keep this issue open up until we **attempt** to build an omemo library for go. When and if that happens, then we will add the supported XEP and versions.

I should also add that you should not count on this project to become anything good in the coming years. It's a learning project, we are not devs. Maybe this works out, maybe not.

Best regards

**Comment by Neustradamus** [comment]
@davidmuradov: Thanks for your answer!

Do you know?
- https://github.com/wstrm/go-omemo
- https://github.com/wstrm/omemo-utils
- https://github.com/roobre/omemo-wget
- https://github.com/joinself/self-crypto-go

**Comment by davidmuradov** [comment]
I am aware of

- https://github.com/joinself/self-crypto-go

I'll look into the three other repositories eventually

Thank you

**Comment by davidmuradov** [comment]
@Neustradamus I've made a repo for the omemo library and added version numbers, XEP, and a link to the repo in README.md.

Closing the issue.
